name: "Deploy Helm to AKS"
description: "Deploys a helm chart to AKS"

inputs:
  azure_client_id:
    description: "azure_client_id"
    required: true
  azure_subscription_id:
    description: "azure_subscription_id"
    required: true
  azure_tenant_id:
    description: "azure_tenant_id"
    required: true
  cluster_name:
    description: "Name of AKS cluster"
    required: true
  resource_group:
    description: "Resource group of AKS cluster"
    required: true
  registry_host:
    description: "Image registry host e.g. myacr.azureacr.io"
    required: true
  chart:
    description: "Chart name"
    required: true
  chart_root:
    description: "Root folder of chart"
    required: true
  namespace:
    description: "Namespace to deploy to"
    required: true

runs:
  using: "composite"
  steps:
  - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
    with:
      client-id: ${{ inputs.azure_client_id }}
      subscription-id: ${{ inputs.azure_subscription_id }}
      tenant-id: ${{ inputs.azure_tenant_id }}

  - uses: azure/use-kubelogin@v1
    name: Set up kubelogin for non-interactive login
    with:
      kubelogin-version: v0.0.25

  - uses: azure/aks-set-context@v3
    name: Get K8s context
    with:
      admin: "false"
      cluster-name: ${{ inputs.cluster_name }}
      resource-group: ${{ inputs.resource_group }}
      use-kubelogin: "true"
  
  - name: Set branch name as env variable
    shell: bash
    run: |
      currentbranch=$(echo ${GITHUB_REF##*/})
      echo "running on $currentbranch"
      echo "BRANCH=$currentbranch" >> $GITHUB_ENV
  
  - name: Deploy Chart
    shell: bash
    run: |
      ./deploy-chart.sh -c ${{ inputs.chart }} --dns aks --aks-name ${{ inputs.clusteR_name }} --aks-rg ${{ inputs.resource_group }} -r ${{ inputs.registry_host }} -t $TAG --namespace ${{ inputs.namespace }} --acr-connected
    env:
      TAG: ${{ env.BRANCH }}
    working-directory: ${{ inputs.chart_root }}